.TH CLIENT 3 "2026" "libmyutils 1.0" "Library Functions Manual"
.SH NAME
client \- test driver for the libmyutils library
.SH SYNOPSIS
.B client
.SH DESCRIPTION
.B client
is a test program that demonstrates and verifies the functionality of the libmyutils library. It tests string functions (mystrlen, mystrcpy, mystrncpy, mystrcat) and file functions (wordCount, mygrep).
.SH AUTHOR
Atif Hussain <muradali356@gmail.com>
